In [2]:
import numpy as np

In [ ]:
np.zeros((3, 4)) 
# создает массив из нулей размером 3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((2, 4), dtype=int) 
# создает массив из нулей размером 2x4 с типом данных int

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
np.ones((5,3), dtype=int)  
# создает массив из единиц размером 5x3 с типом данных int 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.random.seed(0) 
# устанавливает начальное значение генератора случайных 
# чисел для воспроизводимости результатов 
# этот метод нужно вызывать в той же ячейке где 
# генерируются случайные числа
np.random.random((2,4)) 
# создает массив размером 2x4 с случайными числами от 0 до 1 

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])