In [1]:
import numpy as np 

In [2]:
first = np.array([[1, 2, 3], [4, 5, 6,]]) # 2D array
first

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
first.shape 
# размерность массива (2 строки, 3 столбца)

(2, 3)

In [4]:
first.ndim
# количество осей (измерений) массива

2

In [5]:
second = np.array([[7, 8, 9], [10, 11, 12]]) # 2D array
second


array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
second.shape 
# размерность массива (2 строки, 3 столбца)

(2, 3)

In [7]:
first + second
# поэлементное сложение двух массивов

array([[ 8, 10, 12],
       [14, 16, 18]])

In [8]:
first + 1 # прибавление скаляра ко всем элементам массива 

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
first - 2 # вычитание скаляра из всех элементов массива

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [10]:
first * 2 # умножение всех элементов массива на скаляр

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [11]:
first / 3 # деление всех элементов массива на скаляр

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [12]:
first # получение всех элементов массива

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
first[1, 1]  # получение элемента из второй строки и второго столбца

np.int64(5)

In [14]:
np.concatenate((first, second)) 
# объединение двух массивов по строкам (по умолчанию вертикально axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.concatenate((first, second), axis=1) 
# объединение двух массивов по столбцам (горизонтально axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8]))) 
# объединение одномерных массивов по умолчанию вертикально (axis=0)
# одномерные массивы не имеют столбцов, поэтому axis=1 здесь не применимо

array([1, 2, 3, 4, 5, 6, 7, 8])