In [1]:
import numpy as np

In [2]:
np.arange(10)  
# создает одномерный массив с числами от 0 до 9 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(15, 25) 
# создает одномерный массив с числами от 15 до 24

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(20, 30, 3)
# создает одномерный массив с числами от 20 до 29 с шагом 3

array([20, 23, 26, 29])

In [5]:
np.arange(start=-15, stop=5, step=4) 
# создает одномерный массив с числами от -15 до 4 с шагом 4

array([-15, -11,  -7,  -3,   1])

In [6]:
np.arange(20).reshape([2, 10]) 
# преобразует одномерный массив из 20 элементов в двумерный массив 
# размером 2 строки на 10 столбцов

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [7]:
np.arange(20).reshape([2, 2, 5]) 
# преобразует одномерный массив из 20 элементов в трехмерный массив 
# размером 2 блока на 2 строки и 5 столбцов

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
np.arange(20).reshape([4,5]) 
# преобразует одномерный массив из 20 элементов в двумерный массив
# размером 4 строки на 5 столбцов

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
np.random.random((10)).reshape([2,5])
# создает одномерный массив из 10 случайных чисел от 0 до 1 и
# преобразует его в двумерный массив размером 2 строки на 5 столбцов

array([[0.1290139 , 0.34528452, 0.32300746, 0.77716518, 0.69880897],
       [0.15962573, 0.64566892, 0.69858832, 0.52450144, 0.07997455]])

In [10]:
np.random.seed(10) 
# устанавливает начальное значение генератора
# случайных чисел для воспроизводимости
np.random.random((10)).reshape([2,5]) 
# создает одномерный массив из 10 случайных чисел от 0 до 1 и
# преобразует его в двумерный массив размером 2 строки на 5 столбцов    

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [ ]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3)).flatten()
# создает трехмерный массив размером 4 блока на 3 строки и 3 столбца
# с случайными целыми числами от 50 до 79
# и преобразует его в одномерный массив при помощи flatten

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69], dtype=int32)