In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([10.99, 23.99, 5.99, 99.99, 45.99])
# цены товаров в магазине
prices

array([10.99, 23.99,  5.99, 99.99, 45.99])

In [3]:
quantities = np.array([2, 1, 4, 1, 3])
# количество проданных товаров  
quantities 

array([2, 1, 4, 1, 3])

In [4]:
revenue_per_product = prices * quantities
# общая выручка по каждому товару   
revenue_per_product

array([ 21.98,  23.99,  23.96,  99.99, 137.97])

In [5]:
total_revenue = np.sum(revenue_per_product)
# общая выручка за все товары   
total_revenue

np.float64(307.89)

## 2. Analyzing Blog Post Stats 

In [6]:
views = np.array([1500, 2300, 1200, 3400, 2900, 3100])
# количество просмотров каждого поста в блоге
views

array([1500, 2300, 1200, 3400, 2900, 3100])

In [7]:
max_views = np.max(views)
# максимальное количество просмотров среди всех постов
max_views

np.int64(3400)

In [8]:
min_views = np.min(views)
# минимальное количество просмотров среди всех постов
min_views

np.int64(1200)

In [9]:
avarege_views = np.round(np.mean(views), 2)
# среднее количество просмотров среди всех постов
avarege_views 

np.float64(2400.0)

In [10]:
total_views = np.sum(views)
# общее количество просмотров всех постов
total_views

np.int64(14400)

## 3. Splitting Order Into Batches 

In [11]:
order_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108]) 
# идентификаторы заказов
order_ids 

array([101, 102, 103, 104, 105, 106, 107, 108])

In [12]:
batches = np.split(order_ids, 4) 
# разбиваем массив заказы на 4 партии при помощи функции split
batches

[array([101, 102]), array([103, 104]), array([105, 106]), array([107, 108])]

In [13]:
for batch in batches: # проходим по каждой партии заказов
    print(batch) 
    # выводим каждую партию заказов отдельно 

[101 102]
[103 104]
[105 106]
[107 108]


## 4. Categorizing Product Ratings 

In [14]:
ratings = np.array([4.5, 3.8, 4.9, 2.5, 4.0, 3.2, 5.3, 4.7])
# рейтинги продуктов       
ratings  

array([4.5, 3.8, 4.9, 2.5, 4. , 3.2, 5.3, 4.7])

In [15]:
positive_ratings = ratings[ratings >= 4.0] 
#  фильтруем рейтинги, оставляя только положительные (4.0 и выше) 
print("Положительные рейтинги:", positive_ratings) 
# выводим положительные рейтинги

Положительные рейтинги: [4.5 4.9 4.  5.3 4.7]


In [16]:
negative_ratings = ratings[ratings < 4.0] 
#  фильтруем рейтинги, оставляя только отрицательные (ниже 4.0) 
print("Отрицательные рейтинги:", negative_ratings)  
# выводим отрицательные рейтинги

Отрицательные рейтинги: [3.8 2.5 3.2]


## 5. Calculate Total and Avarage quantities sold

In [17]:
order_quantities = np.array([[5, 12, 7, 4], [20, 15, 8, 10]])
# количество заказанных товаров в разных магазинах 
# (строки - магазины, столбцы - товары)
order_quantities

array([[ 5, 12,  7,  4],
       [20, 15,  8, 10]])

In [18]:
total_quantities_per_store = np.sum(order_quantities)
# общее количество заказанных товаров в каждом магазине
total_quantities_per_store

np.int64(81)

In [19]:
sum_quantities_per_product = np.sum(order_quantities, axis=0)
# общее количество заказанных товаров по каждому товару
sum_quantities_per_product

array([25, 27, 15, 14])

In [20]:
sum_quantities_per_order = np.sum(order_quantities, axis=1)
# общее количество заказанных товаров по каждому заказу
sum_quantities_per_order 

array([28, 53])

In [21]:
average_quantities_sold = np.mean(order_quantities, axis=0)
# среднее количество заказанных товаров по каждому товару
average_quantities_sold 

array([12.5, 13.5,  7.5,  7. ])