In [1]:
import numpy as np

In [2]:
np.zeros((3, 4)) 
# создает массив из нулей размером 3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.zeros((2, 4), dtype=int) 
# создает массив из нулей размером 2x4 с типом данных int

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((5, 3), dtype=int)  
# создает массив из единиц размером 5x3 с типом данных int 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.random.seed(0)
# устанавливает начальное значение генератора случайных 
# чисел для воспроизводимости результатов 
# этот метод нужно вызывать в той же ячейке где 
# генерируются случайные числа
np.random.random((2, 4)) 
# создает массив размером 2x4 с случайными числами от 0 до 1 

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [ ]:
np.random.seed(1) 
# устанавливает начальное значение генератора случайных чисел
np.random.randint(10, 20, size=(2, 4))
 # создает массив размером 2x4 с случайными целыми числами от 10 до 19

array([[15, 18, 19, 15],
       [10, 10, 11, 17]], dtype=int32)

In [33]:
np.random.seed(2) 
# устанавливает начальное значение генератора случайных чисел
np.random.uniform(10.0, 50.0, size=(3, 5)) 
# создает массив размером 3x5 с случайными числами с 
# плавающей точкой от 10.0 до 50.0

array([[27.43979609, 11.03704927, 31.98649912, 27.4128957 , 26.81471208],
       [23.21339284, 18.18594536, 34.77083865, 21.98618695, 20.673091  ],
       [34.84535331, 31.16568377, 15.38319781, 30.54312485, 17.37759463]])

In [32]:
np.random.seed(3) 
# устанавливает начальное значение генератора случайных чисел
np.random.choice(np.array([1,2,3]), size=10) 
# создает одномерный массив из 10 случайных элементов, выбранных из 
# переданного массива [1,2,3] с равной вероятностью   

array([3, 1, 2, 1, 1, 1, 2, 2, 3, 2])

In [36]:
np.random.seed(1)
# устанавливает начальное значение генератора случайных чисел
np.random.choice(np.array(['a','b','c','d']), size=15) 
# создает одномерный массив из 15 случайных элементов, выбранных из 
# переданного массива ['a','b','c','d'] с равной вероятностью

array(['b', 'd', 'a', 'a', 'd', 'b', 'd', 'b', 'd', 'a', 'a', 'b', 'a',
       'd', 'b'], dtype='<U1')