In [64]:
import numpy as np

## 1. Calculating Total Revenue

In [65]:
prices = np.array([10.99, 23.99, 5.99, 99.99, 45.99])
# цены товаров в магазине
prices

array([10.99, 23.99,  5.99, 99.99, 45.99])

In [66]:
quantities = np.array([2, 1, 4, 1, 3])
# количество проданных товаров  
quantities 

array([2, 1, 4, 1, 3])

In [67]:
revenue_per_product = prices * quantities
# общая выручка по каждому товару   
revenue_per_product

array([ 21.98,  23.99,  23.96,  99.99, 137.97])

In [68]:
total_revenue = np.sum(revenue_per_product)
# общая выручка за все товары   
total_revenue

np.float64(307.89)

## 2. Analyzing Blog Post Stats 

In [69]:
views = np.array([1500, 2300, 1200, 3400, 2900, 3100])
# количество просмотров каждого поста в блоге
views

array([1500, 2300, 1200, 3400, 2900, 3100])

In [70]:
max_views = np.max(views)
# максимальное количество просмотров среди всех постов
max_views

np.int64(3400)

In [71]:
min_views = np.min(views)
# минимальное количество просмотров среди всех постов
min_views

np.int64(1200)

In [72]:
avarege_views = np.round(np.mean(views), 2)
# среднее количество просмотров среди всех постов
avarege_views 

np.float64(2400.0)

In [73]:
total_views = np.sum(views)
# общее количество просмотров всех постов
total_views

np.int64(14400)

## 3. Splitting Order Into Batches 

In [74]:
order_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108]) 
# идентификаторы заказов
order_ids 

array([101, 102, 103, 104, 105, 106, 107, 108])

In [75]:
batches = np.split(order_ids, 4) 
# разбиваем массив заказы на 4 партии при помощи функции split
batches

[array([101, 102]), array([103, 104]), array([105, 106]), array([107, 108])]

In [76]:
for batch in batches: # проходим по каждой партии заказов
    print(batch) 
    # выводим каждую партию заказов отдельно 

[101 102]
[103 104]
[105 106]
[107 108]


## 4. Categorizing Product Ratings 

In [77]:
ratings = np.array([4.5, 3.8, 4.9, 2.5, 4.0, 3.2, 5.3, 4.7])
# рейтинги продуктов       
ratings  

array([4.5, 3.8, 4.9, 2.5, 4. , 3.2, 5.3, 4.7])

In [78]:
positive_ratings = ratings[ratings >= 4.0] 
#  фильтруем рейтинги, оставляя только положительные (4.0 и выше) 
print("Положительные рейтинги:", positive_ratings) 
# выводим положительные рейтинги

Положительные рейтинги: [4.5 4.9 4.  5.3 4.7]


In [79]:
negative_ratings = ratings[ratings < 4.0] 
#  фильтруем рейтинги, оставляя только отрицательные (ниже 4.0) 
print("Отрицательные рейтинги:", negative_ratings)  
# выводим отрицательные рейтинги

Отрицательные рейтинги: [3.8 2.5 3.2]


## 5. Calculate Total and Avarage quantities sold

In [80]:
order_quantities = np.array([[5, 12, 7, 4], [20, 15, 8, 10]])
# количество заказанных товаров в разных магазинах 
# (строки - магазины, столбцы - товары)
order_quantities

array([[ 5, 12,  7,  4],
       [20, 15,  8, 10]])

In [81]:
total_quantities_per_store = np.sum(order_quantities)
# общее количество заказанных товаров в каждом магазине
total_quantities_per_store

np.int64(81)

In [82]:
sum_quantities_per_product = np.sum(order_quantities, axis=0)
# общее количество заказанных товаров по каждому товару
sum_quantities_per_product

array([25, 27, 15, 14])

In [83]:
sum_quantities_per_order = np.sum(order_quantities, axis=1)
# общее количество заказанных товаров по каждому заказу
sum_quantities_per_order 

array([28, 53])

In [84]:
average_quantities_sold = np.mean(order_quantities, axis=0)
# среднее количество заказанных товаров по каждому товару
average_quantities_sold 

array([12.5, 13.5,  7.5,  7. ])

## 6. Calculate Average product Rating and Maximum rating per Category


In [85]:
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
    ])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [86]:
# Среднее значение по вертикали по столбцам оси 0
averange_product_category = np.mean(product_ratings, axis=0)
averange_product_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [87]:
# Средний рейтинг по отдельному товару по оси 1 горизонтально    
averange_product_category = np.mean(product_ratings, axis=1)
averange_product_category

array([3.8  , 3.475, 2.7  ])

In [88]:
# Максимальное значение по товару по оси 0
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of the sample stock data 


In [ ]:
# первая часть создания трехмерного массива с данными
companies = ['Google', 'Microsoft', 'Apple'] # ось 0 (axis_0)
days = ['Mon 1 April', 'Tue 2 April'] # ось 1  (axis_1)
price_types = ['Open', 'Close', 'High', 'Low'] # ось 2 (axis_2)

In [ ]:
# (3, 2, 4) форма создания трехмерного массива с рандомными данными
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices
# создал рандом 3-х мерный массив из ранее выше созданых значений и округлил значение

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [91]:
stock_prices.shape 
# форма созданного массива

(3, 2, 4)

In [92]:
# три вложенных цикла при помощи которых идет доступ к индексу по определенный оси
# ранее созданного трехмерного массива
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for the {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day}')
        for index_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}')
        print('')
    print('')

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


