In [1]:
import pandas as pd # импортируем библиотеку pandas
import numpy as np  # импортируем библиотеку numpy

## Data Frame 


In [2]:
forum_users = {
    'User_ID': np.array([1, 2, 3, 4, 5]),
    'Username': ['Bogdan_s', 'Jane_Smith', 'Alex123', 'Bob56', 'Mark_Wilson'],
    'Age': [18, 35, 25, 38, 33],
    'Joined date': pd.to_datetime(['2032-01-01', '2032-02-10', '2032-01-19', '2032-01-25', '2032-03-15']),
    'Total Posts': [150, 230, 80, 420, 310],
    'Reputation': [500, 720, 200, 940, 500]
} 

df = pd.DataFrame(forum_users)  # create DataFrame from the   
df

User_ID     Username  Age Joined date  Total Posts  Reputation
0        1     Bogdan_s   18  2032-01-01          150         500
1        2   Jane_Smith   35  2032-02-10          230         720
2        3      Alex123   25  2032-01-19           80         200
3        4        Bob56   38  2032-01-25          420         940
4        5  Mark_Wilson   33  2032-03-15          310         500

In [3]:
df.shape # узнаем размерность DataFrame

(5, 6)

In [4]:
type(df) # узнаем тип данных

pandas.core.frame.DataFrame

In [5]:
df.columns # узнаем тип данных столбцов

Index(['User_ID', 'Username', 'Age', 'Joined date', 'Total Posts',
       'Reputation'],
      dtype='object')

In [6]:
type(df.columns) # преобразуем названия столбцов в список    

pandas.core.indexes.base.Index

In [7]:
df.columns.tolist() # преобразуем названия столбцов в список

['User_ID', 'Username', 'Age', 'Joined date', 'Total Posts', 'Reputation']

In [8]:
df.index.to_list() # преобразуем индексы в список

[0, 1, 2, 3, 4]

In [9]:
df.dtypes # узнаем типы данных в каждом столбце

User_ID                 int64
Username               object
Age                     int64
Joined date    datetime64[ns]
Total Posts             int64
Reputation              int64
dtype: object

In [10]:
df.values # узнаем тип данных

array([[1, 'Bogdan_s', 18, Timestamp('2032-01-01 00:00:00'), 150, 500],
       [2, 'Jane_Smith', 35, Timestamp('2032-02-10 00:00:00'), 230, 720],
       [3, 'Alex123', 25, Timestamp('2032-01-19 00:00:00'), 80, 200],
       [4, 'Bob56', 38, Timestamp('2032-01-25 00:00:00'), 420, 940],
       [5, 'Mark_Wilson', 33, Timestamp('2032-03-15 00:00:00'), 310, 500]],
      dtype=object)

In [11]:
type(df.values) # узнаем тип данных

numpy.ndarray

In [12]:
df.values[1,1] # таким образом можно обратиться к конкретному элементу массива

'Jane_Smith'

In [13]:
df.head() # просмотр первых 5 строк DataFrame

User_ID     Username  Age Joined date  Total Posts  Reputation
0        1     Bogdan_s   18  2032-01-01          150         500
1        2   Jane_Smith   35  2032-02-10          230         720
2        3      Alex123   25  2032-01-19           80         200
3        4        Bob56   38  2032-01-25          420         940
4        5  Mark_Wilson   33  2032-03-15          310         500

In [14]:
df.head(3)  # просмотр первых 3 строк DataFrame

User_ID    Username  Age Joined date  Total Posts  Reputation
0        1    Bogdan_s   18  2032-01-01          150         500
1        2  Jane_Smith   35  2032-02-10          230         720
2        3     Alex123   25  2032-01-19           80         200

In [15]:
df.tail(3) # просмотр последних 3 строк DataFrame

User_ID     Username  Age Joined date  Total Posts  Reputation
2        3      Alex123   25  2032-01-19           80         200
3        4        Bob56   38  2032-01-25          420         940
4        5  Mark_Wilson   33  2032-03-15          310         500

In [16]:
df.describe() # получение статистического резюме по числовым столбцам DataFrame
# этот метод нужно использовать в первую очередь для первичного анализа данных

User_ID        Age          Joined date  Total Posts  Reputation
count  5.000000   5.000000                    5     5.000000    5.000000
mean   3.000000  29.800000  2032-02-01 04:48:00   238.000000  572.000000
min    1.000000  18.000000  2032-01-01 00:00:00    80.000000  200.000000
25%    2.000000  25.000000  2032-01-19 00:00:00   150.000000  500.000000
50%    3.000000  33.000000  2032-01-25 00:00:00   230.000000  500.000000
75%    4.000000  35.000000  2032-02-10 00:00:00   310.000000  720.000000
max    5.000000  38.000000  2032-03-15 00:00:00   420.000000  940.000000
std    1.581139   8.167007                  NaN   133.304163  276.622486

In [17]:
df.describe().round(2) 
# получение статистического резюме по числовым столбцам 
# DataFrame с округлением до 2 знаков

User_ID    Age          Joined date  Total Posts  Reputation
count     5.00   5.00                    5          5.0        5.00
mean      3.00  29.80  2032-02-01 04:48:00        238.0      572.00
min       1.00  18.00  2032-01-01 00:00:00         80.0      200.00
25%       2.00  25.00  2032-01-19 00:00:00        150.0      500.00
50%       3.00  33.00  2032-01-25 00:00:00        230.0      500.00
75%       4.00  35.00  2032-02-10 00:00:00        310.0      720.00
max       5.00  38.00  2032-03-15 00:00:00        420.0      940.00
std       1.58   8.17                  NaN        133.3      276.62

In [18]:
import sys # импортируем библиотеку sys
import pandas as pd # импортируем библиотеку pandas
print(sys.executable) # путь к интерпретатору Python
print(pd.__version__) # версия pandas


c:\Jupyter_notebook\PandasCourse\.venv\Scripts\python.exe
2.3.3


In [19]:
df.select_dtypes(include=['object']) # выбор столбцов с типом данных object

Username
0     Bogdan_s
1   Jane_Smith
2      Alex123
3        Bob56
4  Mark_Wilson

In [20]:
df.select_dtypes(include=['int64']) # выбор столбцов с типом данных int64    

User_ID  Age  Total Posts  Reputation
0        1   18          150         500
1        2   35          230         720
2        3   25           80         200
3        4   38          420         940
4        5   33          310         500

In [21]:
df.isna() # проверка на наличие пропущенных значений

User_ID  Username    Age  Joined date  Total Posts  Reputation
0    False     False  False        False        False       False
1    False     False  False        False        False       False
2    False     False  False        False        False       False
3    False     False  False        False        False       False
4    False     False  False        False        False       False

In [22]:
df.isna().sum() # подсчет количества пропущенных значений в каждом столбце

User_ID        0
Username       0
Age            0
Joined date    0
Total Posts    0
Reputation     0
dtype: int64

## Series 

In [23]:
df['User_ID'] # подсчет количества пропущенных значений в столбце 'User_ID'

0    1
1    2
2    3
3    4
4    5
Name: User_ID, dtype: int64

In [24]:
df['Username'] # подсчет количества пропущенных значений в столбце 'Username'

0       Bogdan_s
1     Jane_Smith
2        Alex123
3          Bob56
4    Mark_Wilson
Name: Username, dtype: object

In [25]:
type(df['Username']) # узнаем тип данных столбца 'Username'

pandas.core.series.Series

In [26]:
username_series = df['Username']
username_series  # сохраняем столбец 'Username' в переменную user_names


0       Bogdan_s
1     Jane_Smith
2        Alex123
3          Bob56
4    Mark_Wilson
Name: Username, dtype: object

In [27]:
type(username_series)  # узнаем тип данных переменной user_names

pandas.core.series.Series

In [28]:
username_series.values  # получаем значения из Series user_names

array(['Bogdan_s', 'Jane_Smith', 'Alex123', 'Bob56', 'Mark_Wilson'],
      dtype=object)

In [29]:
type(username_series.values)  # получаем значения из Series user_names

numpy.ndarray

In [30]:
username_series.index  # получаем индексы из Series user_names

RangeIndex(start=0, stop=5, step=1)

In [31]:
df['Username'].value_counts()  # подсчет уникальных значений в столбце 'Username'

Username
Bogdan_s       1
Jane_Smith     1
Alex123        1
Bob56          1
Mark_Wilson    1
Name: count, dtype: int64

In [32]:
df['Reputation'].value_counts()  # подсчет уникальных значений в столбце 'Reputation'   

Reputation
500    2
720    1
200    1
940    1
Name: count, dtype: int64

In [33]:
df['Reputation'].value_counts(ascending=True) # подсчет уникальных значений в столбце 'Reputation'
# в порядке возрастания

Reputation
720    1
200    1
940    1
500    2
Name: count, dtype: int64

In [34]:
df['Reputation'].unique()  # получение уникальных значений в столбце 'Reputation'

array([500, 720, 200, 940])

In [35]:
df['Username'].sort_values(ascending=False) # сортировка значений в столбце 'Username' 
# в порядке убывания

4    Mark_Wilson
1     Jane_Smith
0       Bogdan_s
3          Bob56
2        Alex123
Name: Username, dtype: object

In [36]:
df['Username'].sort_values() # сортировка значений в столбце 'Username' 
# в порядке возрастания по умолчанию (ASC = ascending = True) 

2        Alex123
3          Bob56
0       Bogdan_s
1     Jane_Smith
4    Mark_Wilson
Name: Username, dtype: object

In [37]:
df['Reputation'].unique() # получение уникальных значений в столбце 'Reputation'

array([500, 720, 200, 940])

In [38]:
df['Reputation'].sort_values(ascending=True) # сортировка значений в столбце 'Reputation'

2    200
0    500
4    500
1    720
3    940
Name: Reputation, dtype: int64