In [3]:
import numpy as np

In [ ]:
arr = np.array([0,1,2,3,4]) # создание одномерного массива
arr 


array([0, 1, 2, 3, 4])

In [ ]:
arr = np.zeros((2,5)) # метод zeros создание массива с значениями "0"
# двухмерный 2х5
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones = np.ones((3,3)) # метод создания массива с значениями "1"
# трехмерный 3х3
ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])