In [2]:
import numpy as np

## Создание массивов 

In [3]:
arr = np.array([0,1,2,3,4]) # создание одномерного массива
arr # по умолчанию ось "0"


array([0, 1, 2, 3, 4])

In [4]:
arr = np.zeros((2,5)) # метод zeros создание массива с значениями "0"
# двухмерный 2х5
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
ones = np.ones((3,3)) # метод создания массива с значениями "1"
# трехмерный 3х3
ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr = np.arange(0,20,4) # создание массива от 0 до 20 с шагом 4
arr 

array([ 0,  4,  8, 12, 16])

In [7]:
arr = np.linspace(0, 21, num=8) 
# создаёт массив, равномерно распределяя числа между началом и концом.
arr  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [8]:
full_arr = np.full((2,3),7) 
# создает массив с параметрами 2x3 и конекртено заданным числом 7
full_arr

array([[7, 7, 7],
       [7, 7, 7]])

## Виды массивов

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
# метод показывает сколько уровней у массива
arr.ndim

2

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# .shape показывает размерность массива.
# Он возвращает кортеж Для 2D — (строки, столбцы).
# Для 3D — (глубина, строки, столбцы)
arr.shape 

(2, 3)

In [11]:
matrix = np.eye(3) # создает матрицу с цифрой 1 по диоганали, все остальное 0
matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
random_array = np.random.rand(2, 3) 
# создание массива с параметрами 2x3 с рандомными числами от 0 до 1
random_array 

array([[0.07580407, 0.58255135, 0.81716808],
       [0.20374064, 0.01817628, 0.76414032]])

In [13]:
random_integers = np.random.randint(1, 10, size=(3, 3)) 
# рандомный 3x3 массив только с заданым диапазоном чисел 1-10
random_integers

array([[2, 9, 3],
       [9, 4, 2],
       [1, 7, 3]], dtype=int32)

In [14]:
arr = np.random.rand(3,3) 
print(f"Ndim = {arr.ndim}")
print(f"Shape = {arr.shape}")


Ndim = 2
Shape = (3, 3)


In [15]:
# Решение задачи построение массива с диапазоном от 10 до 99 с размеров 5x2
arr = np.random.randint(10, 100, size=(5, 2))
arr

array([[79, 97],
       [87, 10],
       [75, 17],
       [66, 43],
       [58, 55]], dtype=int32)

## Теория: типы данных в NumPy

In [16]:
#Основные типы:
# int — целые числа (например, int32, int64). Подходят для счёта, индексов.

# uint — целые числа без знака (uint8, uint16). Нет отрицательных значений.

# float — вещественные числа (float32, float64). Для точных вычислений и дробей.

# complex — комплексные числа (complex64, complex128). Используются в науке и физике.

# bool — логические значения (True или False).

# string — строки, текстовые данные.

# object — любые объекты Python (редко используется в аналитике).

In [17]:
arr = np.array([1, 2, 3])
# позволяет узнать тип данных массива
arr.dtype  

dtype('int64')

In [18]:
arr_f = np.array([1, 2, 3], dtype=np.float32) 
# создание массива с указанием типа данных float32
arr_f.dtype

dtype('float32')

In [19]:
arr_float = arr.astype(np.float64) 
# позволяет изменить тип данных массива
arr_float


array([1., 2., 3.])

In [20]:
arr_float.dtype # проверка типа данных после изменения типа

dtype('float64')

## Практические задания

In [21]:
arr1 = np.array([2, 1, 10])
arr2 = np.array([1, 1, 3])
result = arr1 + arr2 
result # сложение двух массивов поэлементно

array([ 3,  2, 13])

In [22]:
arr1 = np.array([[4, 2, 6],
                 [12, 4, 8],
                 [6, 12, 16]])
result = arr1 / 2
result  # деление всех элементов массива на 2


array([[2., 1., 3.],
       [6., 2., 4.],
       [3., 6., 8.]])

In [23]:
arr1 = np.array([[5, 5, 5],
                 [5, 5, 5],
                 [5, 5, 5]])
arr2 = np.array([[5, 5, 5],
                 [5, 5, 5],
                 [5, 5, 5]])
result = arr1 + arr2
result  # сложение двух матриц поэлементно


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
result = arr1 ** 2
result  # возведение всех элементов массива в квадрат


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
vector = np.array([1, 10, 100])
scalar = 2
result = vector * scalar
result # умножение каждого элемента вектора на скаляр

array([  2,  20, 200])

In [26]:
matrix = np.eye(3)
result = matrix * 5
result # умножение каждого элемента матрицы на скаляр

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [27]:
import numpy as np

matrix_a = np.array([[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]])

matrix_b = np.array([[10, 20, 30],
                     [80, 100, 120],
                     [210, 240, 270]])

result = np.matmul(matrix_a, matrix_b)
result  # умножение двух матриц

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

## Срезы 

In [28]:
## rr[start:stop:step]

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2] # получение каждого второго элемента массива

array([0, 2, 4, 6, 8])

In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1:5] # получение элементов с индекса 1 по индекс 4 (5 не включительно)

array([1, 2, 3, 4])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 # получение всех элементов массива в обратном порядке 
arr[::-1]
 # Напомню, если вы хотите взять последний элемент массива,
 # то нужно обратиться следующим образом: 
 #arr[-1]
 # Тк индексация с конца начинается не с 0, а с -1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
# Срезы в матрицах (2D)  
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix[1, :] # получение всех элементов второй строки матрицы

array([4, 5, 6])

In [32]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix[:, 1] # получение всех элементов второго столбца матрицы

array([2, 5, 8])

In [33]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix[:2, :2] # получение элементов первых двух строк и первых двух столбцов матрицы

array([[1, 2],
       [4, 5]])

In [34]:
## Срезы в трёхмерных массивах (3D) 
tensor = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
]) 
tensor[1, :, :] # получение всех элементов второго "слоя" (глубины) тензора


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
tensor = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
]) 
tensor[:, :, 1] # получение всех элементов второго столбца во всех "слоях" тензора

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [36]:
tensor = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
tensor[:2, :2, :2] # получение элементов первых двух "слоев", 
 #первых двух строк и первых двух столбцов тензора

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
# Транспонирование — это операции, которые позволяют изменять форму 
# (или структуру) массивов в языке программирования Python, 
# особенно при использовании библиотеки NumPy.
# 1. T (транспонирование): 
# Метод T используется для транспонирования массива, 
# меняя местами строки и столбцы.
# numpy.ndarray.T

In [ ]:
arr = np.array([[1, 4, 31], [4, 52, 6]])
transposed_arr = arr.T # транспонирование массива
print("Исходный массив:")
print(arr)
print("\nТранспонированный массив:")
print(transposed_arr)

Исходный массив:
[[ 1  4 31]
 [ 4 52  6]]

Транспонированный массив:
[[ 1  4]
 [ 4 52]
 [31  6]]
