In [1]:
import numpy as np

## Создание массивов 

In [2]:
arr = np.array([0,1,2,3,4]) # создание одномерного массива
arr 


array([0, 1, 2, 3, 4])

In [3]:
arr = np.zeros((2,5)) # метод zeros создание массива с значениями "0"
# двухмерный 2х5
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
ones = np.ones((3,3)) # метод создания массива с значениями "1"
# трехмерный 3х3
ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr = np.arange(0,20,4) # создание массива от 0 до 20 с шагом 4
arr 

array([ 0,  4,  8, 12, 16])

In [6]:
arr = np.linspace(0, 21, num=8) 
# создаёт массив, равномерно распределяя числа между началом и концом.
arr  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [7]:
full_arr = np.full((2,3),7) 
# создает массив с параметрами 2x3 и конекртено заданным числом 7
full_arr

array([[7, 7, 7],
       [7, 7, 7]])

## Виды массивов

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
# метод показывает сколько уровней у массива
arr.ndim

2

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# .shape показывает размерность массива.
# Он возвращает кортеж Для 2D — (строки, столбцы).
# Для 3D — (глубина, строки, столбцы)
arr.shape 

(2, 3)

In [10]:
matrix = np.eye(3) # создает матрицу с цифрой 1 по диоганали, все остальное 0
matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
random_array = np.random.rand(2, 3) 
# создание массива с параметрами 2x3 с рандомными числами от 0 до 1
random_array 

array([[0.30062206, 0.61559975, 0.39427419],
       [0.6934033 , 0.30397802, 0.43218843]])

In [12]:
random_integers = np.random.randint(1, 10, size=(3, 3)) 
# рандомный 3x3 массив только с заданым диапазоном чисел 1-10
random_integers

array([[3, 2, 2],
       [2, 6, 4],
       [4, 2, 8]], dtype=int32)

In [13]:
arr = np.random.rand(3,3) 
print(f"Ndim = {arr.ndim}")
print(f"Shape = {arr.shape}")


Ndim = 2
Shape = (3, 3)


In [14]:
# Решение задачи построение массива с диапазоном от 10 до 99 с размеров 5x2
arr = np.random.randint(10, 100, size=(5, 2))
arr

array([[53, 71],
       [72, 80],
       [26, 84],
       [80, 42],
       [76, 32]], dtype=int32)

## Теория: типы данных в NumPy

In [15]:
#Основные типы:
# int — целые числа (например, int32, int64). Подходят для счёта, индексов.

# uint — целые числа без знака (uint8, uint16). Нет отрицательных значений.

# float — вещественные числа (float32, float64). Для точных вычислений и дробей.

# complex — комплексные числа (complex64, complex128). Используются в науке и физике.

# bool — логические значения (True или False).

# string — строки, текстовые данные.

# object — любые объекты Python (редко используется в аналитике).

In [16]:
arr = np.array([1, 2, 3])
# позволяет узнать тип данных массива
arr.dtype  

dtype('int64')

In [17]:
arr_f = np.array([1, 2, 3], dtype=np.float32)
arr_f.dtype

dtype('float32')

In [18]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [19]:
arr_float = arr.astype(np.float64) 
# позволяет изменить тип данных массива
arr_float


array([1., 2., 3.])

In [20]:
arr_float.dtype 

dtype('float64')