In [1]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4]) # создание одномерного массива
arr 


array([0, 1, 2, 3, 4])

In [3]:
arr = np.zeros((2,5)) # метод zeros создание массива с значениями "0"
# двухмерный 2х5
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
ones = np.ones((3,3)) # метод создания массива с значениями "1"
# трехмерный 3х3
ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr = np.arange(0,20,4) # создание массива от 0 до 20 с шагом 4
arr 

array([ 0,  4,  8, 12, 16])